##Fixed yaml for zap
env:
  contexts:
  - name: Default Context
    urls:
    - "https://brokencrystals.com" #changed
    #- https://brokencrystals.com.*
    authentication:
      method: form
      parameters:
        loginRequestUrl: https://brokencrystals.com/api/auth/login
        loginRequestBody: "user=[%username%]&password=[%password%]&op=html"
        loginPageUrl: https://brokencrystals.com/userlogin
      verification:
        method: response
        loggedInRegex: Log out
        loggedOutRegex: Sign in
        pollFrequency: 60
        pollUnits: requests
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: cookie
    technology: {}
    structure: {}
    users:
    - name: "admin@admin.com" #changed
      credentials:
        password: "PASSWORD" #admin #changed
        username: "USERNAME" #admin@admin.com #changed
  parameters: {}
jobs:
- type: passiveScan-config
  parameters: {}
- type: spider
  parameters:
    context: Default Context
    user: admin@admin.com
    url: https://brokencrystals.com
    maxDepth: 0
    handleODataParametersVisited: true
    maxParseSizeBytes: 1255032704
    parseDsStore: null
    logoutAvoidance: true
  tests:
  - name: At least 100 URLs found
    type: stats
    onFail: INFO
    statistic: automation.spider.urls.added
    operator: '>='
    value: 100
- type: spiderAjax
  parameters:
    context: Default Context
    user: admin@admin.com
    url: https://brokencrystals.com
    numberOfBrowsers: 1
    browserId: null
- type: passiveScan-wait
  parameters: {}
- type: report
  parameters: ###from here, added
    template: "traditional-html"
    reportDir: "CI_PROJECT_DIR"
    reportFile: "ZAP_REPORT"
    reportTitle: "ZAP Baseline Scan Report"
    reportDescription: ""
    displayReport: false
  risks:
  - "info"
  - "low"
  - "medium"
  - "high"
  confidences:
  - "falsepositive"
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  sections:
  - "instancecount"
  - "alertdetails"
  - "alertcount"
  name: "report"
  type: "report"
- parameters:
    template: "traditional-md"
    reportDir: "CI_PROJECT_DIR"
    reportFile: "ZAP_ALERT_REPORT"
    reportTitle: "ZAP Scanning Report"
    reportDescription: "This is report that should contain only alerts that should
       fail the pipeline and be revisited by a team member"
    displayReport: false
  risks:
  - "low"
  - "medium"
  - "high"
  confidences:
  - "low"
  - "medium"
  - "high"   
  - "confirmed"
  sections:
  - "alertdetails"
  - "alertcount"
  name: "alert-report"
  type: "report"